name = "AdaptiveOpticsHIL"
uuid = "c50291de-c366-4d66-93e5-abfdaae8bfec"
version = "0.1.0"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]

[deps]
AdaptiveOpticsSim = "002fb5eb-ad68-44a0-adbe-b299bfc2febc"
Agent = "f7939a7f-2bcc-4096-952b-c44031b5533b"
Clocks = "6b5ade5d-6e95-4584-b343-73eec2e8782b"

[sources]
AdaptiveOpticsSim = {url = "https://github.com/DarrylGamroth/AdaptiveOpticsSim.jl.git", rev = "a73d41cdeaec162b672913cf8707ff04e2710d13"}
Agent = {url = "https://github.com/DarrylGamroth/Agent.jl.git", rev = "71e3af4e5c112f0433e03d57a570bc74ffd05ccc"}
Clocks = {url = "https://github.com/DarrylGamroth/Clocks.jl.git", rev = "1b705421648b70b6d171f8a95d6c2d16c2444d0b"}

[compat]
AdaptiveOpticsSim = "0.1"
Agent = "0.4.1"
Aqua = "0.8"
Clocks = "0.3"
InteractiveUtils = "1"
LinearAlgebra = "1"
Test = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "InteractiveUtils", "LinearAlgebra", "Test"]
