"""
    Timing

Versioned mapping from external timestamp domains into canonical plant time,
and mapping between that plant timeline and an injected monotonic host
execution clock. This namespace converts and measures time; it does not
synchronize external clocks, sleep, poll, advance plant time, or own a
scheduler.
"""
module Timing

import Clocks
using AdaptiveOpticsSim.Plant: PlantDuration, PlantTimestamp
using AdaptiveOpticsSim.Plant: plant_nanoseconds

import ..AdaptiveOpticsHIL: AdaptiveOpticsHILError

include("timing/external_timestamps.jl")
include("timing/execution_clock.jl")

export TimestampMappingError
export ExternalTimestampDomainID, TimestampMappingVersion
export TimestampMappingOwnerID, ExternalTimestampMapping
export MappedExternalTimestamp, PreparedTimestampMappings
export prepare_timestamp_mappings, install_timestamp_mapping!
export map_external_timestamp, timestamp_mapping, latest_timestamp_mapping
export timestamp_mapping_at, timestamp_mapping_count
export timestamp_mapping_capacity, timestamp_mapping_owner
export external_timestamp_domain, timestamp_mapping_version
export source_timestamp_ticks, mapped_plant_timestamp
export timestamp_mapping_uncertainty
export source_anchor_ticks, plant_anchor_timestamp
export timestamp_rate_numerator, timestamp_rate_denominator
export timestamp_valid_from_ticks, timestamp_valid_through_ticks

export ExecutionClockError, ExecutionClockID, ExecutionClockUpdateOwnerID
export CachedExecutionClock, CachedExecutionClockController
export ExecutionClockMapping, ExecutionClockMetadata
export prepare_cached_execution_clock, cached_execution_clock
export refresh_cached_execution_clock!
export cached_clock_update_owner, cached_clock_update_cadence_ns
export cached_clock_maximum_observed_staleness_ns
export cached_clock_refresh_count
export arm_execution_clock
export execution_clock, execution_clock_identity, execution_clock_metadata
export execution_clock_source_provider, execution_clock_update_owner
export execution_clock_update_cadence_ns
export execution_clock_maximum_observed_staleness_ns
export execution_clock_refresh_count
export plant_time_origin, execution_clock_origin_ns
export execution_lateness_ns, execution_time_until_ns

end
